apiVersion: v1
kind: ConfigMap
metadata:
  name: envik-config
  namespace: envik
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__Redis: "redis-service:6379"
  JwtSettings__Issuer: "envik-server"
  JwtSettings__Audience: "envik-client"
  JwtSettings__AccessTokenExpiryMinutes: "15"
  JwtSettings__RefreshTokenExpiryDays:  "7"